name: "Tags"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: "Target Tag"
        type: string
        required: true
      tags:
        description: "Extra Tags"
        type: string
        required: false
      major:
        description: "Parse Major"
        type: boolean
        default: true
      minor:
        description: "Parse Minor"
        type: boolean
        default: true

jobs:
  tags:
    name: "Tags"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      packages: write

    steps:
      - name: "Update Tags"
        uses: smashedr/update-version-tags-action@master
        with:
          target: ${{ inputs.target }}
          tags: ${{ inputs.tags }}
          major: "${{ inputs.major != '' && inputs.major || true }}"
          minor: "${{ inputs.minor != '' && inputs.minor || true }}"
